# This file was generated by GoReleaser. DO NOT EDIT.
cask "amnesia" do
  binary "amnesia", target: "age-plugin-amnesia"

  name "amnesia"
  desc ""
  homepage ""
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "amnesia"

  on_macos do
    on_intel do
      url "https://github.com/cedws/amnesia/releases/download/v#{version}/amnesia_#{version}_darwin_amd64.tar.gz"
      sha256 "96c77bfaf94441130e11ac832be5e9bc22438c02ca37225c2dda39d42e56a998"
    end
    on_arm do
      url "https://github.com/cedws/amnesia/releases/download/v#{version}/amnesia_#{version}_darwin_arm64.tar.gz"
      sha256 "7bbdc4b40800ddffad4b270216e95bc29749b0a23bd7490daeec1a54a605ade9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cedws/amnesia/releases/download/v#{version}/amnesia_#{version}_linux_amd64.tar.gz"
      sha256 "9068aaa78e5667f0758d14b3b8f919100dcf59bdf93e13c6f3df4233de7c695f"
    end
    on_arm do
      url "https://github.com/cedws/amnesia/releases/download/v#{version}/amnesia_#{version}_linux_arm64.tar.gz"
      sha256 "828dcdbcd5b42ca527ccd52def05f51509743694ff360de4afb3d91eefaa13c7"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/amnesia"]
    end
  end

  # No zap stanza required
end
