# This file was generated by GoReleaser. DO NOT EDIT.
cask "amnesia" do
  binary "amnesia", target: "age-plugin-amnesia"

  desc ""
  homepage ""
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "amnesia"

  on_macos do
    on_intel do
      url "https://github.com/cedws/amnesia/releases/download/v0.1.0/amnesia_0.1.0_darwin_amd64.tar.gz"
      sha256 "ddbabec3e8d50278b8f84610f96ec5c3b2b601b9da0714f0b715c97b77a2f5bf"
    end
    on_arm do
      url "https://github.com/cedws/amnesia/releases/download/v0.1.0/amnesia_0.1.0_darwin_arm64.tar.gz"
      sha256 "dcb71bcb350fd5d83926392a29363c1e54d4671570c12b9086999efeaf90d609"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cedws/amnesia/releases/download/v0.1.0/amnesia_0.1.0_linux_amd64.tar.gz"
      sha256 "3cc83210225608d8d1fcf114d5de14dd8a2f5c5cbabeb8d630755f39fb93138b"
    end
    on_arm do
      url "https://github.com/cedws/amnesia/releases/download/v0.1.0/amnesia_0.1.0_linux_arm64.tar.gz"
      sha256 "ccc929ffa28b3db5704b160b723d15c01b9370f3c5797f10a0915dd7a861b9ab"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/amnesia"]
    end
  end

  # No zap stanza required
end
