# This file was generated by GoReleaser. DO NOT EDIT.
cask "crush" do
  name "crush"
  desc "Unofficial fork of Crush — a powerful terminal-based AI assistant for developers."
  homepage "https://github.com/cedws/crush"
  version "0.39.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "crush"

  on_macos do
    on_intel do
      url "https://github.com/cedws/crush/releases/download/v#{version}/crush_#{version}_Darwin_x86_64.tar.gz"
      sha256 "52763c540f9bc8245ab3cf0fa5c31afc6e65a5f25fd3522b4fae816a954ea193"
    end
    on_arm do
      url "https://github.com/cedws/crush/releases/download/v#{version}/crush_#{version}_Darwin_arm64.tar.gz"
      sha256 "53daf2ed451751745785e45cb396684c3219755e37cf8d19eef701c5d8413d79"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cedws/crush/releases/download/v#{version}/crush_#{version}_Linux_x86_64.tar.gz"
      sha256 "6a4509e59e5e970f4a32498bbdc2c487679b21733dc52941fe74f3713ca435ef"
    end
    on_arm do
      url "https://github.com/cedws/crush/releases/download/v#{version}/crush_#{version}_Linux_arm64.tar.gz"
      sha256 "5d26f01e50e63b5ffaf646173f18de16d5f32185868ed06d2970c6ffe5cd6a8e"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/crush"]
    end
  end

  # No zap stanza required
end
