# This file was generated by GoReleaser. DO NOT EDIT.
cask "gh-webhook-broker" do
  binary "gh-webhook-broker", target: "gh-webhook-wait"
  binary "gh-webhook-broker", target: "gh-webhook-subscribe"

  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/cedws/gh-webhook-broker/releases/download/v#{version}/gh-webhook-broker_#{version}_darwin_amd64.tar.gz"
      sha256 "339098b72d840653c4690b6d0104dd7e04b948be05890864230f95ade7720b27"
    end
    on_arm do
      url "https://github.com/cedws/gh-webhook-broker/releases/download/v#{version}/gh-webhook-broker_#{version}_darwin_arm64.tar.gz"
      sha256 "0300046c7d6a995becc757f82ffec5c565e4575f7af9ce9ebd9599d55cc982a5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cedws/gh-webhook-broker/releases/download/v#{version}/gh-webhook-broker_#{version}_linux_amd64.tar.gz"
      sha256 "56d256536143df0b8b4277faa784d8bb270822d31828fc0301ccf33596ba2081"
    end
    on_arm do
      url "https://github.com/cedws/gh-webhook-broker/releases/download/v#{version}/gh-webhook-broker_#{version}_linux_arm64.tar.gz"
      sha256 "ea3902ed45dc39db18d980111ab6005ddf337da7fc82b3286f8fd0bd8f3f2266"
    end
  end

  name "gh-webhook-broker"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gh-webhook-broker"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gh-webhook-broker"]
    end
  end

  # No zap stanza required

end
