# This file was generated by GoReleaser. DO NOT EDIT.
cask "iapc" do
  desc ""
  homepage ""
  version "0.1.10"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "iapc"

  on_macos do
    on_intel do
      url "https://github.com/cedws/iapc/releases/download/v0.1.10/iapc_0.1.10_darwin_amd64.tar.gz"
      sha256 "7098598ae78b8c52c998e8e3168792827c89bd8b8029dffb79502d8fc8813325"
    end
    on_arm do
      url "https://github.com/cedws/iapc/releases/download/v0.1.10/iapc_0.1.10_darwin_arm64.tar.gz"
      sha256 "77e3be69be87f1135006a00e70ee8f01fdc7dec1b40ebd6a660a67613afe4dbc"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cedws/iapc/releases/download/v0.1.10/iapc_0.1.10_linux_amd64.tar.gz"
      sha256 "bc1b860361e5dad9645afdfbd48b827291fff43a1850fdcbf646bd113f8b7215"
    end
    on_arm do
      url "https://github.com/cedws/iapc/releases/download/v0.1.10/iapc_0.1.10_linux_arm64.tar.gz"
      sha256 "cea79a95d06f5618fa238017a0d0577051272932eb92f9c5587b37068d56b4d1"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/iapc"]
    end
  end

  # No zap stanza required
end
