# This file was generated by GoReleaser. DO NOT EDIT.
cask "iapc" do
  version "0.1.12"

  on_macos do
    on_intel do
      url "https://github.com/cedws/iapc/releases/download/v#{version}/iapc_#{version}_darwin_amd64.tar.gz"
      sha256 "af3568121ee859d3fbeb396f260bf697ec38c8ee4ac004ef50d1b7f5c5199ac2"
    end
    on_arm do
      url "https://github.com/cedws/iapc/releases/download/v#{version}/iapc_#{version}_darwin_arm64.tar.gz"
      sha256 "8cd5ce793050fec4f374ced2a2cb2f2846b747aa371d5eed4d145c787c904654"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cedws/iapc/releases/download/v#{version}/iapc_#{version}_linux_amd64.tar.gz"
      sha256 "031b0c5c55bd82777d48f87d58f38b7f0d2ab02ed318cb7a79c3bf6d62fac89c"
    end
    on_arm do
      url "https://github.com/cedws/iapc/releases/download/v#{version}/iapc_#{version}_linux_arm64.tar.gz"
      sha256 "c51fdc30dc738f0f081a3795eddc5935e6bc8dfebdbc6bbf2ec5d16bf2e30867"
    end
  end

  name "iapc"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "iapc"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/iapc"]
    end
  end

  # No zap stanza required

end
