# This file was generated by GoReleaser. DO NOT EDIT.
cask "ki-keyring" do
  version "0.2.4"

  on_macos do
    on_intel do
      url "https://github.com/cedws/ki-keyring/releases/download/v#{version}/ki-keyring_#{version}_darwin_amd64.tar.gz"
      sha256 "de8b0636f7c3c2d559a7bc9ad6eb564b860e458e33166a94e5fc1ae5b954e8a3"
    end
    on_arm do
      url "https://github.com/cedws/ki-keyring/releases/download/v#{version}/ki-keyring_#{version}_darwin_arm64.tar.gz"
      sha256 "40e38015fbb9bf08572fff167e5f44ae04419a58e44a57baf8e048d86bd4b1a0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cedws/ki-keyring/releases/download/v#{version}/ki-keyring_#{version}_linux_amd64.tar.gz"
      sha256 "76e8eadd3ad6463ed1cf789512e33dd52a5e31eeb6fac5d4e679274f5233cde4"
    end
    on_arm do
      url "https://github.com/cedws/ki-keyring/releases/download/v#{version}/ki-keyring_#{version}_linux_arm64.tar.gz"
      sha256 "1199c36a3151298972e94ab254f8cc41d9fa499dbfa3312676788c650a87c233"
    end
  end

  name "ki-keyring"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ki-keyring"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ki-keyring"]
    end
  end

  # No zap stanza required

end
