# This file was generated by GoReleaser. DO NOT EDIT.
cask "nyse-trade-halts" do
  name "nyse-trade-halts"
  desc ""
  homepage ""
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nyse-trade-halts"

  on_macos do
    on_intel do
      url "https://github.com/cedws/nyse-trade-halts/releases/download/v#{version}/nyse-trade-halts_#{version}_darwin_amd64.tar.gz"
      sha256 "ea135d27c98eb2122caa52f7c70e50e3dff9963351a4fb15bebf155ff4ed2000"
    end
    on_arm do
      url "https://github.com/cedws/nyse-trade-halts/releases/download/v#{version}/nyse-trade-halts_#{version}_darwin_arm64.tar.gz"
      sha256 "a4dd69e58ccc67af2b410a1396ca1fb64c426bc394073c451814a275f3f4b3df"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cedws/nyse-trade-halts/releases/download/v#{version}/nyse-trade-halts_#{version}_linux_amd64.tar.gz"
      sha256 "66fe444313e719b2fcc01543d54e3ca9dcb3db5dfe36f30f96452395330c1c17"
    end
    on_arm do
      url "https://github.com/cedws/nyse-trade-halts/releases/download/v#{version}/nyse-trade-halts_#{version}_linux_arm64.tar.gz"
      sha256 "62b37f501b798aeea5aaa02a3f7bef66fd2ba475ed1b6569f6189f76681ce19e"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nyse-trade-halts"]
    end
  end

  # No zap stanza required
end
