# This file was generated by GoReleaser. DO NOT EDIT.
cask "nyse-trade-halts" do
  desc ""
  homepage ""
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nyse-trade-halts"

  on_macos do
    on_intel do
      url "https://github.com/cedws/nyse-trade-halts/releases/download/v0.1.0/nyse-trade-halts_0.1.0_darwin_amd64.tar.gz"
      sha256 "a0ace1d8c67ba31fde27ca8ce1f55531a9144f305c4de091318d141fc7b5fccf"
    end
    on_arm do
      url "https://github.com/cedws/nyse-trade-halts/releases/download/v0.1.0/nyse-trade-halts_0.1.0_darwin_arm64.tar.gz"
      sha256 "9ed7b8a9b681d74be3d3e06cce1562e6a4055622940bcb379daeb705dc550cb7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cedws/nyse-trade-halts/releases/download/v0.1.0/nyse-trade-halts_0.1.0_linux_amd64.tar.gz"
      sha256 "d8283dbccd224ed2a4f10db0dfe1feda18456a4e78a645edef8606fa883b5909"
    end
    on_arm do
      url "https://github.com/cedws/nyse-trade-halts/releases/download/v0.1.0/nyse-trade-halts_0.1.0_linux_arm64.tar.gz"
      sha256 "04bfa5e6adbecd084e9fb375b0ef16f0db4dd040deae1d1b7a176d614005f2f3"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nyse-trade-halts"]
    end
  end

  # No zap stanza required
end
