# This file was generated by GoReleaser. DO NOT EDIT.
cask "nyse-trade-halts" do
  binary "amnesia", target: "age-plugin-amnesia"

  name "nyse-trade-halts"
  desc ""
  homepage ""
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nyse-trade-halts"

  on_macos do
    on_intel do
      url "https://github.com/cedws/nyse-trade-halts/releases/download/v#{version}/nyse-trade-halts_#{version}_darwin_amd64.tar.gz"
      sha256 "bbb653987f5cb61649e99d5d06a02a32f9419d032f8275ce10b5d4bf31936712"
    end
    on_arm do
      url "https://github.com/cedws/nyse-trade-halts/releases/download/v#{version}/nyse-trade-halts_#{version}_darwin_arm64.tar.gz"
      sha256 "4ea64cb13c9a81ecacc183d3da72b7f23100d219fd53f9b74be885eb728f3a9c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cedws/nyse-trade-halts/releases/download/v#{version}/nyse-trade-halts_#{version}_linux_amd64.tar.gz"
      sha256 "58f89ad378230407c052c85802cc3b15253051d0f8d3265e5d2b3a4420afcba7"
    end
    on_arm do
      url "https://github.com/cedws/nyse-trade-halts/releases/download/v#{version}/nyse-trade-halts_#{version}_linux_arm64.tar.gz"
      sha256 "07137201d76562055b9eae2a1652e1fb82c7ebb152d4992a4964b6da53c521ab"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nyse-trade-halts"]
    end
  end

  # No zap stanza required
end
