# This file was generated by GoReleaser. DO NOT EDIT.
cask "proxmox-service-discovery" do
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/cedws/proxmox-service-discovery/releases/download/v#{version}/proxmox-service-discovery_#{version}_darwin_amd64.tar.gz"
      sha256 "f6c7ff5c02f5df6b3ded0184ea78bee8c2c691ccc8755b7c5bd7d267dd5150e7"
    end
    on_arm do
      url "https://github.com/cedws/proxmox-service-discovery/releases/download/v#{version}/proxmox-service-discovery_#{version}_darwin_arm64.tar.gz"
      sha256 "039ec5ac1762aeb1ad1498ea48218b7c0d0db292e79cae1fa89cf4c2ca7fb76b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cedws/proxmox-service-discovery/releases/download/v#{version}/proxmox-service-discovery_#{version}_linux_amd64.tar.gz"
      sha256 "77d24f55b8a9a8d4e158b7ce58ba4f7a4618a21efb616d8bd0486601664a020a"
    end
    on_arm do
      url "https://github.com/cedws/proxmox-service-discovery/releases/download/v#{version}/proxmox-service-discovery_#{version}_linux_arm64.tar.gz"
      sha256 "04db2dc390f352a4027f49b84254ba9a8614ebfc602691a49d6a47b21530eb6b"
    end
  end

  name "proxmox-service-discovery"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "proxmox-service-discovery"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/proxmox-service-discovery"]
    end
  end

  # No zap stanza required

end
