# This file was generated by GoReleaser. DO NOT EDIT.
cask "proxmox-service-discovery" do
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/cedws/proxmox-service-discovery/releases/download/v#{version}/proxmox-service-discovery_#{version}_darwin_amd64.tar.gz"
      sha256 "cfe07ec0b7f692985ccfee41ca27d4ea4a3d689eaa0245fc186c1c648092e149"
    end
    on_arm do
      url "https://github.com/cedws/proxmox-service-discovery/releases/download/v#{version}/proxmox-service-discovery_#{version}_darwin_arm64.tar.gz"
      sha256 "23b10c6aa052f75355fff7b4fb53b7da35878e8e59ff37f28591ec4552443938"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cedws/proxmox-service-discovery/releases/download/v#{version}/proxmox-service-discovery_#{version}_linux_amd64.tar.gz"
      sha256 "7dc0efbcc7ac77f02c6c848f696254e415f519cc8b9438fdce64030f641d7fed"
    end
    on_arm do
      url "https://github.com/cedws/proxmox-service-discovery/releases/download/v#{version}/proxmox-service-discovery_#{version}_linux_arm64.tar.gz"
      sha256 "926b2dea34f280c6bf70f7e7742578146adb9b3df0abc4016349da0ab284ec05"
    end
  end

  name "proxmox-service-discovery"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "proxmox-service-discovery"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/proxmox-service-discovery"]
    end
  end

  # No zap stanza required

end
