# This file was generated by GoReleaser. DO NOT EDIT.
cask "sshgate" do
  version "0.2.1"

  on_macos do
    on_intel do
      url "https://github.com/cedws/sshgate/releases/download/v#{version}/sshgate_#{version}_darwin_amd64.tar.gz"
      sha256 "56ac90f116d10e02ab549fc4bbdd3180dd839b6ed157052081ad5d2bd537ea5d"
    end
    on_arm do
      url "https://github.com/cedws/sshgate/releases/download/v#{version}/sshgate_#{version}_darwin_arm64.tar.gz"
      sha256 "58dda474d0802b44d9b8d5d401c30d3e3dcda2fa95be577282d889b535db1a5d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cedws/sshgate/releases/download/v#{version}/sshgate_#{version}_linux_amd64.tar.gz"
      sha256 "71ae889d9baa5935dd7d8b4195323ae771ac9ef111f6e5332f36b9514adb96ec"
    end
    on_arm do
      url "https://github.com/cedws/sshgate/releases/download/v#{version}/sshgate_#{version}_linux_arm64.tar.gz"
      sha256 "a46d6b6e2d62b8f73d93e31407a1838eafc2690f0876b5ff743e8abfb5f08bf4"
    end
  end

  name "sshgate"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sshgate"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sshgate"]
    end
  end

  # No zap stanza required

end
