# This file was generated by GoReleaser. DO NOT EDIT.
cask "sshgate" do
  desc ""
  homepage ""
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sshgate"

  on_macos do
    on_intel do
      url "https://github.com/cedws/sshgate/releases/download/v0.1.0/sshgate_0.1.0_darwin_amd64.tar.gz"
      sha256 "788141ec7b24c0426f659c339aed87cabd66dac37580973fb18320b14892570a"
    end
    on_arm do
      url "https://github.com/cedws/sshgate/releases/download/v0.1.0/sshgate_0.1.0_darwin_arm64.tar.gz"
      sha256 "9de2ca0157e7270f157bdd4d252fb53ed311f713879562a6b1e3ae29381a2fc4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cedws/sshgate/releases/download/v0.1.0/sshgate_0.1.0_linux_amd64.tar.gz"
      sha256 "47bad24565d6b0fa01ab66eaebd0dde1de4221a1cae4026de1a5bc9e68641907"
    end
    on_arm do
      url "https://github.com/cedws/sshgate/releases/download/v0.1.0/sshgate_0.1.0_linux_arm64.tar.gz"
      sha256 "f597464a42daba6cce0f0fa5eb2b102a32c0cb9dc7575e6953a00bb8e3eb0352"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sshgate"]
    end
  end

  # No zap stanza required
end
