# This file was generated by GoReleaser. DO NOT EDIT.
cask "sshgate" do
  name "sshgate"
  desc ""
  homepage ""
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sshgate"

  on_macos do
    on_intel do
      url "https://github.com/cedws/sshgate/releases/download/v#{version}/sshgate_#{version}_darwin_amd64.tar.gz"
      sha256 "d4077cc849a2b26424e37844b2b682492c263ae2f0aa30e4e5f5b67eb1970ccd"
    end
    on_arm do
      url "https://github.com/cedws/sshgate/releases/download/v#{version}/sshgate_#{version}_darwin_arm64.tar.gz"
      sha256 "0c4e60f1f004fbbc2bcea3bb11cd0e9fa0d4148bd29f560fe7eeb0eeab50baa8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cedws/sshgate/releases/download/v#{version}/sshgate_#{version}_linux_amd64.tar.gz"
      sha256 "6cbc82b4fba2bf47f6a27af6e4300c25198577aa84e2dd2db6adf8228444b31b"
    end
    on_arm do
      url "https://github.com/cedws/sshgate/releases/download/v#{version}/sshgate_#{version}_linux_arm64.tar.gz"
      sha256 "fa6fe390b3dfc9dcae2adb35941881858b3deb9ba753daee8777cc622318dc8f"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sshgate"]
    end
  end

  # No zap stanza required
end
