# This file was generated by GoReleaser. DO NOT EDIT.
cask "umbra-launcher" do
  desc ""
  homepage ""
  version "0.1.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "umbra-launcher"

  on_macos do
    on_intel do
      url "https://github.com/cedws/umbra-launcher/releases/download/v0.1.4/umbra-launcher_0.1.4_darwin_amd64.tar.gz"
      sha256 "ee1e0e8b5f7e8ce1a7e881bb5e6a00f2ec3eea9e245d362c494caf770a92b881"
    end
    on_arm do
      url "https://github.com/cedws/umbra-launcher/releases/download/v0.1.4/umbra-launcher_0.1.4_darwin_arm64.tar.gz"
      sha256 "9737313ffba85ddc8889423eea3bc67cac854e4bd3227b44410452dc979245f0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cedws/umbra-launcher/releases/download/v0.1.4/umbra-launcher_0.1.4_linux_amd64.tar.gz"
      sha256 "4061e889b7e11e47f3e65cb660a2441e15771dcc1057dcbf8aed7baa548bfdda"
    end
    on_arm do
      url "https://github.com/cedws/umbra-launcher/releases/download/v0.1.4/umbra-launcher_0.1.4_linux_arm64.tar.gz"
      sha256 "673ab890aa5b01e7d55d226a05fb8e1187a5a029ebd9b5701c33e3bf7a3d9a52"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/umbra-launcher"]
    end
  end

  # No zap stanza required
end
